name: Trigger auto deployment for container-app-lkisua576635o

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-lkisua576635o-AutoDeployTrigger-c814cba6-c598-407d-8be9-04046fb3ded2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPLKISUA576635O_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPLKISUA576635O_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPLKISUA576635O_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPLKISUA576635O_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPLKISUA576635O_REGISTRY_PASSWORD }}
          containerAppName: container-app-lkisua576635o
          resourceGroup: appspacesragapp925ca397
          imageToBuild: default/container-app-lkisua576635o:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


